# Generated by Django 4.1.5 on 2023-01-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_user_age_remove_user_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('hire', models.CharField(max_length=50)),
                ('sale', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
