# Generated by Django 4.1.5 on 2023-01-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='count',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
