# Generated by Django 4.1.5 on 2023-01-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_car_hire_alter_car_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
