# Generated by Django 4.1.5 on 2023-01-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_car_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='created',
        ),
    ]
