# Generated by Django 4.1.5 on 2023-01-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_car_count_car_created_car_hire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='count',
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
