# Generated by Django 4.1.5 on 2023-01-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_car_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('description', models.TextField(default='', null=True)),
                ('paid', models.BooleanField(default=False)),
                ('returned', models.BooleanField(default=False)),
                ('date_returned', models.DateTimeField(auto_now_add=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
