# Generated by Django 4.1.5 on 2023-01-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_booking_date_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='collected',
            field=models.BooleanField(default=False),
        ),
    ]
