# Generated by Django 4.1.5 on 2023-01-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_booking_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
